In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [3]:
load_iris()

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
iris= load_iris()
dt_clf = DecisionTreeClassifier(random_state=0)

In [5]:
dt_clf

DecisionTreeClassifier(random_state=0)

In [6]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
iris_label = iris.target
iris_label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris_df = pd.DataFrame(data=iris.data, columns= iris.feature_names)
iris_df["label"] = iris.target
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [9]:
from sklearn.model_selection import train_test_split, KFold

In [10]:
# 
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris_label,
                                                    train_size=0.8, random_state=100000)

In [11]:
X_train

array([[5. , 3. , 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [4.7, 3.2, 1.3, 0.2],
       [6.8, 2.8, 4.8, 1.4],
       [5.8, 2.8, 5.1, 2.4],
       [6. , 2.9, 4.5, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [5.3, 3.7, 1.5, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 3.3, 4.7, 1.6],
       [6.7, 3. , 5.2, 2.3],
       [5. , 3.5, 1.3, 0.3],
       [5.5, 4.2, 1.4, 0.2],
       [6.7, 3. , 5. , 1.7],
       [4.9, 2.5, 4.5, 1.7],
       [4.9, 3.1, 1.5, 0.1],
       [7.7, 3. , 6.1, 2.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.2, 4.1, 1.5, 0.1],
       [5.1, 3.8, 1.6, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [4.6, 3.2, 1.4, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [5.6, 2.9, 3.6, 1.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.3, 3.3, 6. , 2.5],
       [5.1, 3.5, 1.4, 0.2],
       [6.9, 3.1, 5.1, 2.3],
       [6.3, 2.8, 5.1, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.5, 4. , 1.3],
       [6.9, 3.1, 4.9, 1.5],
       [5.8, 2

In [12]:
X_train.shape

(120, 4)

In [13]:
dt_clf = DecisionTreeClassifier(random_state=13)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=13)

In [14]:
iris_df[iris_df["label"]==0].describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           50.00000         50.000000          50.000000   
mean             5.00600          3.428000           1.462000   
std              0.35249          0.379064           0.173664   
min              4.30000          2.300000           1.000000   
25%              4.80000          3.200000           1.400000   
50%              5.00000          3.400000           1.500000   
75%              5.20000          3.675000           1.575000   
max              5.80000          4.400000           1.900000   

       petal width (cm)  label  
count         50.000000   50.0  
mean           0.246000    0.0  
std            0.105386    0.0  
min            0.100000    0.0  
25%            0.200000    0.0  
50%            0.200000    0.0  
75%            0.300000    0.0  
max            0.600000    0.0

In [15]:
dt_clf.feature_importances_

array([0.01669101, 0.01251826, 0.04809701, 0.92269373])

In [16]:
pred = dt_clf.predict(X_test)
pred
iris_df[iris_df["label"]==0].describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           50.00000         50.000000          50.000000   
mean             5.00600          3.428000           1.462000   
std              0.35249          0.379064           0.173664   
min              4.30000          2.300000           1.000000   
25%              4.80000          3.200000           1.400000   
50%              5.00000          3.400000           1.500000   
75%              5.20000          3.675000           1.575000   
max              5.80000          4.400000           1.900000   

       petal width (cm)  label  
count         50.000000   50.0  
mean           0.246000    0.0  
std            0.105386    0.0  
min            0.100000    0.0  
25%            0.200000    0.0  
50%            0.200000    0.0  
75%            0.300000    0.0  
max            0.600000    0.0

In [17]:
X_test

array([[5.5, 2.3, 4. , 1.3],
       [6. , 3.4, 4.5, 1.6],
       [6. , 3. , 4.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [4.4, 3. , 1.3, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [6.4, 2.8, 5.6, 2.1],
       [5.7, 4.4, 1.5, 0.4],
       [5. , 3.2, 1.2, 0.2],
       [5.8, 2.7, 3.9, 1.2],
       [4.9, 2.4, 3.3, 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.2, 3.5, 1.5, 0.2],
       [6.5, 3. , 5.8, 2.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.6, 2.5, 3.9, 1.1],
       [6.6, 3. , 4.4, 1.4],
       [5. , 3.6, 1.4, 0.2],
       [6. , 2.2, 4. , 1. ],
       [4.3, 3. , 1.1, 0.1],
       [6.1, 2.6, 5.6, 1.4],
       [5. , 3.4, 1.6, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [5.7, 2.9, 4.2, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [6.9, 3.2, 5.7, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.5, 3. , 5.2, 2. ]])

In [18]:
pred

array([1, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0,
       2, 0, 0, 1, 1, 2, 2, 2])

In [19]:
y_test

array([1, 1, 2, 1, 0, 0, 0, 0, 2, 0, 0, 1, 1, 1, 0, 2, 0, 1, 1, 0, 1, 0,
       2, 0, 0, 1, 1, 2, 2, 2])

In [20]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

1.0

In [21]:
features = iris.data
label = iris.target
kfold = KFold(n_splits=5)
cv_accuracy=[]

In [22]:
kfold

KFold(n_splits=5, random_state=None, shuffle=False)

In [23]:
n_iter=0
cv_accuracy=[]
for i, j in kfold.split(features):
    X_train, X_test = features[i], features[j]
    y_train , y_test = label[i], label[j]
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    print(y_train)
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy.append(accuracy)
    

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0

In [24]:
print(cv_accuracy)
print(np.mean(cv_accuracy))

[1.0, 1.0, 0.8667, 0.9333, 0.7333]
0.9066599999999999


In [25]:
features = iris.data
label = iris.target
kfold2 = KFold(n_splits=3)
cv_accuracy2=[]

In [26]:
n_iter=0

for train_index, test_index in kfold2.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train , y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy2.append(accuracy)
    

In [27]:
print(cv_accuracy2)
print(np.mean(cv_accuracy2))

[0.0, 0.0, 0.0]
0.0


In [28]:
iris = load_iris()

iris_df = pd.DataFrame(data=iris.data,columns=iris.feature_names)
iris_df["label"] = iris.target
iris_df["label"].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [29]:
kfold= KFold(n_splits=3)
n_iter = 0
for train_index, test_index in kfold.split(iris_df):
    n_iter +=1
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(label_train.value_counts())
    print(label_test.value_counts())

label
1    50
2    50
Name: count, dtype: int64
label
0    50
Name: count, dtype: int64
label
0    50
2    50
Name: count, dtype: int64
label
1    50
Name: count, dtype: int64
label
0    50
1    50
Name: count, dtype: int64
label
2    50
Name: count, dtype: int64


In [30]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
n_iter = 0
for train_index, test_index in skf.split(iris_df,iris_df['label']):
    n_iter +=1
    label_train = iris_df["label"].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(label_train.value_counts())
    print(label_test.value_counts())

label
2    34
0    33
1    33
Name: count, dtype: int64
label
0    17
1    17
2    16
Name: count, dtype: int64
label
1    34
0    33
2    33
Name: count, dtype: int64
label
0    17
2    17
1    16
Name: count, dtype: int64
label
0    34
1    33
2    33
Name: count, dtype: int64
label
1    17
2    17
0    16
Name: count, dtype: int64


In [31]:
skfold = StratifiedKFold(n_splits=3)
n_iter = 0
cv_accuracy3=[]
for train_index, test_index in skfold.split(features,label):
    X_train, X_test = features[train_index], features[test_index]
    y_train , y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train, y_train)
    pred = dt_clf.predict(X_test)
    
    n_iter +=1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    cv_accuracy3.append(accuracy)

print(np.round(cv_accuracy3,4))
print(np.mean(cv_accuracy3))

[0.98 0.92 1.  ]
0.9666666666666667


In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate

In [33]:
iris_data= load_iris()
dt_clf = DecisionTreeClassifier(random_state=152)

data = iris_data.data
label = iris_data.target

scores = cross_val_score(dt_clf,data,label,scoring='accuracy',cv=10)
print(np.round(scores,4))
print(np.round(np.mean(scores),4))

[1.     0.9333 1.     0.9333 0.9333 0.8667 0.9333 1.     1.     1.    ]
0.96
